[package]
name = "emi_deprecated_models-aliquoting_data"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde.workspace = true
diesel-builders.workspace = true
diesel.workspace = true
validation-errors.workspace = true
rosetta_timestamp.workspace = true
rosetta_uuid.workspace = true
emi_deprecated_models-containers.workspace = true
emi_deprecated_models-si_units.workspace = true
emi_deprecated_models-directus_users.workspace = true

[lints]
workspace = true
